### PR TITLE
Add: Lighshot, Hot, Tiles apps

### PR DESCRIPTION
**Pull request by oguzhantasimaz**

### CODE REVIEW

**Comment by hasantezcan** [comment]
Thanks for your contribution @oguzhantasimaz We decided to remove the id property from the data json. Could you pls remove the id property and commit again? Then we can merge your branch to the master.

**Comment by alpercun** [comment]
@oguzhantasimaz can you update the PR based on the comment?

**Review by alpercun — APPROVED** [review]

**Comment by alpercun** [comment]
Conflict 💀 @oguzhantasimaz

**Comment by oguzhantasimaz** [comment]
@alpercun resolved, sorry for delay I was moving to new town

**Review by alpercun — APPROVED** [review]

**Pull request merged**
