### PR TITLE
feat: introduces issue templates

### PR DESCRIPTION
**Pull request by volkanto**
see the title...

### CODE REVIEW

**Comment by volkanto** [comment]
@alpercun fyi ☝️

**Comment by alpercun** [comment]
> @alpercun fyi ☝️

A template already exists in constants.js. Why should we add this? @volkanto

**Comment by volkanto** [comment]
> > @alpercun fyi ☝️
> 
> A template already exists in constants.js. Why should we add this? @volkanto

This will enable you to add a template into issues section. There is no hint that shows the issue template in any places in the repo, just you need to dig yourself to find it. But with this template it will be easy to create issues with given template like below:

image

image

image

**Comment by volkanto** [comment]
@alpercun if you are not convinced I am going to close the PR.

**Review by alpercun — APPROVED** [review]

**Pull request merged**
